name: Releasing APK files
outputs:
  patch_version:
    description: "Latest patch version"
    value: ${{ steps.rv-version.outputs.patch_version }}
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        https://github.com/revanced/revanced-patches/releases
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Get patch version
      shell: bash
      id: rv-version
      run: bash src/etc/check.sh ReVanced/revanced-patches latest
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: ${{ steps.rv-version.outputs.patch_version }}
        tag: ${{ steps.rv-version.outputs.patch_version }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true