name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        
        https://github.com/revanced/revanced-patches/releases
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Get patch version
      shell: bash
      id: get-patch-version
      run: bash src/etc/check.sh ReVanced/revanced-patches latest youtube.apk
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: ${{ steps.get-patch-version.outputs.patch_version }}
        tag: ${{ steps.get-patch-version.outputs.patch_version }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true